sudo: true

language: rust

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential

script:
  - RUSTFLAGS='-C link-args=-s' cargo build -j`nproc` --release
  - cp target/release/nomino .
  - cargo test -j`nproc` --all

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: nomino
  skip_cleanup: true
  on:
    tags: true
