[package]
name = "nomino"
version = "0.1.0"
authors = ["Navid <yaa110@gmail.com>"]
edition = "2018"

[dependencies]

[profile.release]
debug = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
